### ISSUE TITLE
Remove JS only on production build

### ISSUE THREAD

**Issue by mathiasha** [jordanoverbye/gatsby-plugin-no-js#1]
This is a great plugin! Exactly what I was looking for.

Is it possible to only remove JS on `gatsby build`?
I can see Gatsby has some environment variables available, so they might be the solution.

I know this could have some potential issues, since you wouldn't be see the same thing when developing, compared to production build. But it would be nice to have the hot reload then developing.

**Comment by jordanoverbye** [comment]
Hey @mathiasha,

Yeah I agree, this plugin should only trigger when in production mode. I've just pushed a change to fix this.

Thanks for your feedback!
