### ISSUE TITLE
Readme is 

### ISSUE THREAD

**Issue by mathiasha** [jordanoverbye/gatsby-plugin-no-js#3]
In the readme it says that this plugin does not work with images.
That is not correct. This does work with images, it just removes some of the benefits and optimisations you get from Gatsby.

It might be worth pointing to this article for people working with images. https://www.gatsbyjs.org/docs/static-folder/

**Comment by mathiasha** [comment]
I just read the readme again, and i see that you wrote it doesn't work with gatsby-image. However, I think pointing to the article would still be a valid point.

**Comment by jordanoverbye** [comment]
Hey @mathiasha, thanks for your feedback. I have just updated the README to make it a little more clear.
